//
// Created by vallois on 02/07/18.
//
#ifndef ANALYSE_ROOTREADER_H
#define ANALYSE_ROOTREADER_H

#include <string>

#include "TTree.h"
#include "TFile.h"
#include "caloHit.h"

/**
 * \struct RawHit
 * \brief this structure contains the data generated by the simulation
 */
struct RawHit {
    Int_t eventNb;    //!< [in] muon number
    Int_t chamberNb;  //!< [in] chamber number (corresponds to the one noted in the .json)
    Double_t X;       //!< [in] x coordinate (mm)
    Double_t Y;       //!< [in] y coordinate (mm)
    Double_t Z;       //!< [in] z coordinate (mm)
    Double_t time;    //!< [in] time of the muon generation (s)
    Double_t energy;  //!< [in] muon energy (MeV)
};

/**
 * \class RootReader
 * \brief export the data stored in .root
 */
class RootReader {
public:
    RootReader();

    virtual ~RootReader();

    /**
     * \fn void Initialise(const std::string &file_name = "")
     * \brief opens the file "file_name" in the../data/ or by default rawdata_0000.root then gives access to the TTree
     * @param file_name name of the root file to open
     */
    void Initialise(const std::string &file_name = "");

    /**
     * \fn RawHit GetEntry(Long64_t entry)
     * \brief access to ttree row
     * @param entry row number
     * @return RawHit
     */
    RawHit GetEntry(Long64_t entry);

    /**
     * \fn Long64_t GetTreeSize()
     * \brief give the total number of row in the ttree
     * @return TreeSize
     */
    Long64_t GetTreeSize();

private:
    std::string file_name_;
    std::string tree_name_;

    TFile *file_;
    TTree *tree_;

    /// List of Branches
    TBranch *b_eventNb_;
    TBranch *b_chamberNb_;
    TBranch *b_X_;
    TBranch *b_Y_;
    TBranch *b_Z_;
    TBranch *b_time_;
    TBranch *b_energy_;

    /// Declaration of leaf types
    Int_t eventNb_;
    Int_t chamberNb_;
    Double_t X_;
    Double_t Y_;
    Double_t Z_;
    Double_t time_;
    Double_t energy_;
};


#endif //ANALYSE_ROOTREADER_H
